### PR TITLE
Output %w[ord] array

### PR DESCRIPTION
**Pull request by danielbayley**
Cleaner syntax, and now `brew style` compliant.

### CODE REVIEW

**Comment by nrlquaker** [comment]
Why do we need to output `%w`?

**Comment by danielbayley** [comment]
> Why do we need to output `%w`?

> Cleaner syntax, and now `brew style` compliant.

Easier to use a word array when working with a large array of long strings, like when having to add more entries that `createzap` missed… `createzap` is a useful starting point, but doesn't always find everything…

~~~ rb
zap trash: [
  "~/Library/Application Support/Flux",
  "~/Library/Caches/org.herf.Flux",
  "~/Library/Containers/com.justgetflux.flux",
  "~/Library/Cookies/org.herf.Flux.binarycookies",
  "~/Library/Preferences/org.herf.Flux.plist",
]
~~~
vs
~~~ rb
zap trash: %w[
  ~/Library/Application Support/Flux
  ~/Library/Caches/org.herf.Flux
  ~/Library/Containers/com.justgetflux.flux
  ~/Library/Cookies/org.herf.Flux.binarycookies
  ~/Library/Preferences/org.herf.Flux.plist
]
~~~

**Comment by nrlquaker** [comment]
@danielbayley Sorry for a delay.
But I still don't understand why we should output `zap trash: %w[` is zap stanza.
I couldn't found any reference to it in documentation.
Can you explain please?

**Comment by danielbayley** [comment]
> @danielbayley Sorry for a delay. But I still don't understand why we should output `zap trash: %w[` is zap stanza. I couldn't found any reference to it in documentation. Can you explain please?

More info on array literals [here](https://aloucaslabs.com/miniposts/what-is-the-difference-between-w-and-w-array-literals-in-ruby)…

I suppose it’s personal preference… The `brew style` Rubocop doesn’t enforce either style, so up to you really @nrlquaker. I use the latter in my taps, as it’s easier to edit.

**Comment by nrlquaker** [comment]
I want this script to create stanza with the same style as in main repo.
I don't see any array literals there

**Comment by danielbayley** [comment]
> I want this script to create stanza with the same style as in main repo. I don't see any array literals there

Fair enough 👌🏼

**Pull request closed without merging**
